

// Authorization

export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_LOGOUT = 'LOGIN_LOGOUT';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const RECOVERY_REQUEST = 'RECOVERY_REQUEST';
export const RECOVERY_SUCCESS = 'RECOVERY_SUCCESS';
export const RECOVERY_FAILURE = 'RECOVERY_FAILURE';
export const RECOVERY_VERIFICATION_REQUEST = 'RECOVERY_VERIFICATION_REQUEST';
export const RECOVERY_VERIFICATION_SUCCESS = 'RECOVERY_VERIFICATION_SUCCESS';
export const RECOVERY_VERIFICATION_FAILURE = 'RECOVERY_VERIFICATION_FAILURE';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILURE = 'REFRESH_TOKEN_FAILURE';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';

export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';

// Subjects

export const SUBJECTS_REQUEST = 'SUBJECTS_REQUEST';
export const SUBJECTS_SUCCESS = 'SUBJECTS_SUCCESS';
export const SUBJECTS_FAILURE = 'SUBJECTS_FAILURE';

export const SUBJECT_REQUEST = 'SUBJECT_REQUEST';
export const SUBJECT_SUCCESS = 'SUBJECT_SUCCESS';
export const SUBJECT_FAILURE = 'SUBJECT_FAILURE';

export const TOPIC_REQUEST = 'TOPIC_REQUEST';
export const TOPIC_SUCCESS = 'TOPIC_SUCCESS';
export const TOPIC_FAILURE = 'TOPIC_FAILURE';

export const QUESTION_ANSWERED = 'QUESTION_ANSWERED';
export const CURRENT_QUESTION_CHANGED = "CURRENT_QUESTION_CHANGED";
export const TOPIC_TEST_DONE = 'TOPIC_TEST_DONE';
export const TOPIC_TEST_RETRY = 'TOPIC_TEST_RETRY';

export const TASK_REPLIED = 'TASK_REPLIED';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';

export const FRIENDS_LIST_REQUEST = 'FRIENDS_LIST_REQUEST';
export const FRIENDS_LIST_SUCCESS = 'FRIENDS_LIST_SUCCESS';
export const FRIENDS_LIST_FAILURE = 'FRIENDS_LIST_FAILURE';

export const SEARCH_FRIEND_REQUEST = 'SEARCH_FRIEND_REQUEST';
export const SEARCH_FRIEND_SUCCESS = 'SEARCH_FRIEND_SUCCESS';
export const SEND_FRIEND_REQUEST = 'SEND_FRIEND_REQUEST';
export const SEND_FRIEND_REQUEST_SUCCESS = 'SEND_FRIEND_REQUEST_SUCCESS';

export const SELECTIVES_LIST_REQUEST = 'SELECTIVES_LIST_REQUEST';
export const SELECTIVES_LIST_SUCCESS = 'SELECTIVES_LIST_SUCCESS';
export const SELECTIVES_LIST_FAILURE = 'SELECTIVES_LIST_FAILURE';

export const TRIAL_PAGE_REQUEST = 'TRIAL_PAGE_REQUEST';
export const TRIAL_PAGE_SUCCESS = 'TRIAL_PAGE_SUCCESS';
export const TRIAL_PAGE_FAILURE = 'TRIAL_PAGE_FAILURE';

export const TRIAL_TEST_REQUEST = 'TRIAL_TEST_REQUEST';
export const TRIAL_TEST_SUCCESS = 'TRIAL_TEST_SUCCESS';
export const TRIAL_TEST_FAILURE = 'TRIAL_TEST_FAILURE';
export const TRIAL_ANSWER_SELECTED = 'TRIAL_ANSWER_SELECTED';
export const TRIAL_QUESTION_MARKED = 'TRIAL_QUESTION_MARKED';

export const OOF_REQUEST = 'OOF_REQUEST';
export const OOF_SUCCESS = 'OOF_SUCCESS';
export const OOF_FAILURE = 'OOF_FAILURE';

export const NOTIFICATIONS_LIST_REQUEST = 'NOTIFICATIONS_LIST_REQUEST';
export const NOTIFICATIONS_LIST_SUCCESS = 'NOTIFICATIONS_LIST_SUCCESS';
export const NOTIFICATIONS_LIST_FAILURE = 'NOTIFICATIONS_LIST_FAILURE';

export const SUBSCRIPTIONS_REQUEST = 'SUBSCRIPTIONS_REQUEST';
export const SUBSCRIPTIONS_SUCCESS = 'SUBSCRIPTIONS_SUCCESS';
export const SUBSCRIPTIONS_FAILURE = 'SUBSCRIPTIONS_FAILURE';
export const SELECTIVE_CHANGED = 'SELECTIVE_CHANGED';
export const SELECTIVE_PAIR_CHANGED = 'SELECTIVE_PAIR_CHANGED';
export const SUPPORT_AVAILABLE_REFRESH = 'SUPPORT_AVAILABLE_REFRESH';
export const SUPPORT_WRITE_REQUEST = 'SUPPORT_WRITE_REQUEST';
export const SUPPORT_WRITE_SUCCESS = 'SUPPORT_WRITE_SUCCESS';
export const SUPPORT_WRITE_FAILURE = 'SUPPORT_WRITE_FAILURE';
//export const FRIEND_REQUEST_ACCEPTED = 'FRIEND_REQUEST_ACCEPTED';




